### ISSUE TITLE
Overnight Scan Crashed at 7945th Measurement

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#188] opened 2020-06-29 17:51 UTC
@prjemian The overnight scan last night crashed at the 7945th measurement. This time it crashed with an error saying 'Too Many Files Opened' so it's different from the ones we experienced and fixed before.

I sent a screenshot of the LabView panel to the Rigaku people and hopefully they'll start investigating on their side as well. Although cryptic, you can see from the log (the panel on the right) that XSPA received trigger from Bluesky for Acq. 2944 (15:34:14.16) and Acq. 2945 (15:34:19.50), but never for Acq. 2946, which is also where Bluesky crashed.

So this will be a two-pronged investigation: @prjemian Please look at the Bluesky log to see if you spot any abnormal activity and I'll work with the Rigaku team to make sure the detector was functioning properly.

Thanks!

<details>
<summary> Error message on terminal  </summary>

```

S136_TMV_Fly0p1_att00_2940
HDF5 workflow file name: /home/8-id-i/2020-2/comm202006/S136_TMV_Fly0p1_att00_2940/S136_TMV_Fly0p1_att00_2940_0001-100000.hdf     
S136_TMV_Fly0p1_att00_2941                                                                                                        
HDF5 workflow file name: /home/8-id-i/2020-2/comm202006/S136_TMV_Fly0p1_att00_2941/S136_TMV_Fly0p1_att00_2941_0001-100000.hdf     
S136_TMV_Fly0p1_att00_2942
HDF5 workflow file name: /home/8-id-i/2020-2/comm202006/S136_TMV_Fly0p1_att00_2942/S136_TMV_Fly0p1_att00_2942_0001-100000.hdf     
S136_TMV_Fly0p1_att00_2943
HDF5 workflow file name: /home/8-id-i/2020-2/comm202006/S136_TMV_Fly0p1_att00_2943/S136_TMV_Fly0p1_att00_2943_0001-100000.hdf     
S136_TMV_Fly0p1_att00_2944
HDF5 workflow file name: /home/8-id-i/2020-2/comm202006/S136_TMV_Fly0p1_att00_2944/S136_TMV_Fly0p1_att00_2944_0001-100000.hdf     
S136_TMV_Fly0p1_att00_2945
HDF5 workflow file name: /home/8-id-i/2020-2/comm202006/S136_TMV_Fly0p1_att00_2945/S136_TMV_Fly0p1_att00_2945_0001-100000.hdf     
S136_TMV_Fly0p1_att00_2946
Run aborted
Traceback (most recent call last):
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 1353, in _run
    msg = self._plan_stack[-1].send(resp)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1307, in __call__
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1162, in baseline_wrapper
    return (yield from plan_mutator(plan, insert_baseline))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 803, in monitor_during_wrapper
    return (yield from plan2)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 861, in fly_during_wrapper
    return (yield from plan2)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_CPMV.py", line 91, in multi_capil
    yield from repeat_acq(sample_name='TMV_Fly0p1',att_value=0,acq_rep=5000,FLY_YES_NO=True,samx_cen=-4,samz_cen=z0)
  File "/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_CPMV.py", line 73, in repeat_acq
    md={})
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py", line 305, in AD_Acquire
    return (yield from full_acquire_procedure(md=md))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py", line 1046, in dec_inner
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 952, in stage_wrapper
    return (yield from finalize_wrapper(inner(), unstage_devices()))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 509, in finalize_wrapper
    ret = yield from plan
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 950, in inner
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py", line 1046, in dec_inner
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 803, in monitor_during_wrapper
    return (yield from plan2)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py", line 273, in full_acquire_procedure
    yield from inner_count([areadet], md=_md)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py", line 226, in inner_count
    yield from bps.stage(obj)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 698, in stage
    return (yield Msg('stage', obj))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  [Previous line repeated 4 more times]
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 1413, in _run
    new_response = await coro(msg)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 2156, in _stage
    result = obj.stage()
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/devices/rigaku_ufxc.py", line 163, in stage
    self.unix_process.put(cmd)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/devices/rigaku_ufxc.py", line 60, in put
    status = self.set(unix_command)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/devices/rigaku_ufxc.py", line 48, in set
    stderr = subprocess.PIPE,
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/subprocess.py", line 1441, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-30-e00c4c348150> in <module>
----> 1 _ = RE(multi_capil())

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    793             self._task_fut.add_done_callback(set_blocking_event)
    794 
--> 795         self._resume_task(init_func=_build_task)
    796 
    797         if self._interrupted:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _resume_task(self, init_func)
    917                     if (exc is not None
    918                             and not isinstance(exc, _RunEnginePanic)):
--> 919                         raise exc
    920 
    921     def install_suspender(self, suspender):

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1486             exit_reason = str(err)
   1487             self.log.exception("Run aborted")
-> 1488             raise err
   1489         finally:
   1490             if not exit_reason:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1351                     else:
   1352                         try:
-> 1353                             msg = self._plan_stack[-1].send(resp)
   1354                         # We have exhausted the top generator
   1355                         except StopIteration:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1305         plan = monitor_during_wrapper(plan, self.monitors)
   1306         plan = baseline_wrapper(plan, self.baseline)
-> 1307         return (yield from plan)
   1308 
   1309 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1160         return (yield from plan)
   1161     else:
-> 1162         return (yield from plan_mutator(plan, insert_baseline))
   1163 
   1164 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    801     plan1 = plan_mutator(plan, insert_after_open)
    802     plan2 = plan_mutator(plan1, insert_before_close)
--> 803     return (yield from plan2)
    804 
    805 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    859     plan1 = plan_mutator(plan, insert_after_open)
    860     plan2 = plan_mutator(plan1, insert_before_close)
--> 861     return (yield from plan2)
    862 
    863 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_CPMV.py in multi_capil()
     89     yield from repeat_acq(sample_name='TMV',att_value=0,acq_rep=5000,samx_cen=-4,samz_cen=z0)
     90 
---> 91     yield from repeat_acq(sample_name='TMV_Fly0p1',att_value=0,acq_rep=5000,FLY_YES_NO=True,samx_cen=-4,samz_cen=z0)
     92 
     93     bec.enable_plots()

/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_CPMV.py in repeat_acq(areadet, file_header, acq_rep, sample_name, Temp_list, att_value, FLY_YES_NO, samx_cen, samz_cen)
     71             atten=None,
     72             path='/home/8-id-i/2020-2/comm202006/',
---> 73             md={})
     74 
     75     bec.enable_plots()

~/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py in AD_Acquire(areadet, acquire_time, acquire_period, num_images, file_name, submit_xpcs_job, atten, path, md)
    303 
    304     logger.info("calling full_acquire_procedure()")
--> 305     return (yield from full_acquire_procedure(md=md))

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1044                 plan = gen_func(*inner_args, **inner_kwargs)
   1045                 plan = wrapper(plan, *args, **kwargs)
-> 1046                 return (yield from plan)
   1047             return dec_inner
   1048         return dec

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in stage_wrapper(plan, devices)
    950         return (yield from plan)
    951 
--> 952     return (yield from finalize_wrapper(inner(), unstage_devices()))
    953 
    954 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in finalize_wrapper(plan, final_plan, pause_for_debug)
    507     cleanup = True
    508     try:
--> 509         ret = yield from plan
    510     except GeneratorExit:
    511         cleanup = False

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in inner()
    948     def inner():
    949         yield from stage_devices()
--> 950         return (yield from plan)
    951 
    952     return (yield from finalize_wrapper(inner(), unstage_devices()))

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1044                 plan = gen_func(*inner_args, **inner_kwargs)
   1045                 plan = wrapper(plan, *args, **kwargs)
-> 1046                 return (yield from plan)
   1047             return dec_inner
   1048         return dec

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    801     plan1 = plan_mutator(plan, insert_after_open)
    802     plan2 = plan_mutator(plan1, insert_before_close)
--> 803     return (yield from plan2)
    804 
    805 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     76             # if we have a stashed exception, pass it along
     77             try:
---> 78                 msg = plan_stack[-1].throw(exception)
     79             except StopIteration as e:
     80                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     76             # if we have a stashed exception, pass it along
     77             try:
---> 78                 msg = plan_stack[-1].throw(exception)
     79             except StopIteration as e:
     80                 # discard the exhausted generator

~/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py in full_acquire_procedure(md)
    271         logger.debug("before count()")
    272         # yield from bp.count([areadet], md=md)
--> 273         yield from inner_count([areadet], md=_md)
    274         logger.debug("after count()")
    275 

~/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py in inner_count(devices, md)
    224         yield from bps.open_run(md=md)
    225         for obj in devices:
--> 226             yield from bps.stage(obj)
    227         grp = bps._short_uid('trigger')
    228         no_wait = True

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/plan_stubs.py in stage(obj)
    696     :func:`bluesky.plan_stubs.unstage`
    697     """
--> 698     return (yield Msg('stage', obj))
    699 
    700 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1411                         # exceptions (coming in via throw) can be
   1412                         # raised
-> 1413                         new_response = await coro(msg)
   1414 
   1415                     # special case `CancelledError` and let the outer

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _stage(self, msg)
   2154         if not hasattr(obj, 'stage'):
   2155             return []
-> 2156         result = obj.stage()
   2157         self._staged.add(obj)  # add first in case of failure below
   2158         await self._reset_checkpoint_state_coro()

~/.ipython-bluesky/profile_bluesky/startup/instrument/devices/rigaku_ufxc.py in stage(self)
    161         shutter_override.put("High")
    162         cmd = f"echo FILE:F:{self.batch_name.get()} | nc rigaku1.xray.aps.anl.gov 10000"
--> 163         self.unix_process.put(cmd)
    164 
    165     def trigger(self):

~/.ipython-bluesky/profile_bluesky/startup/instrument/devices/rigaku_ufxc.py in put(self, unix_command)
     58 
     59     def put(self, unix_command):
---> 60         status = self.set(unix_command)
     61         while not status.done:
     62             time.sleep(0.01)

~/.ipython-bluesky/profile_bluesky/startup/instrument/devices/rigaku_ufxc.py in set(self, unix_command)
     46             stdin = subprocess.PIPE,
     47             stdout = subprocess.PIPE,
---> 48             stderr = subprocess.PIPE,
     49             )
     50 

~/.conda/envs/bluesky_2020_5/lib/python3.7/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    798                                 c2pread, c2pwrite,
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:
    802             # Cleanup if the child failed starting.

~/.conda/envs/bluesky_2020_5/lib/python3.7/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1439             # Data format: "exception name:hex errno:description"
   1440             # Pickle is not used; it is complex and involves memory allocation.
-> 1441             errpipe_read, errpipe_write = os.pipe()
   1442             # errpipe_write must not be in the standard io 0, 1, or 2 fd range.
   1443             low_fds_to_close = []

OSError: [Errno 24] Too many open files

In [31]:                                                                                                                          


```

</details>

<img width="890" alt="Screen Shot 2020-06-29 at 12 40 34 PM" src="https://user-images.githubusercontent.com/48140482/86038481-9c1df300-ba06-11ea-8ad5-1e588d9ce0e4.png">

**Comment by qzhang234** [comment] 2020-06-29 18:05
Also both /home/8-id-i/ and /home/8-id-i-stage have plenty of space left

<img width="624" alt="Screen Shot 2020-06-29 at 1 04 41 PM" src="https://user-images.githubusercontent.com/48140482/86040194-34b57280-ba09-11ea-9682-4e95df19e0b9.png">

**Comment by prjemian** [comment] 2020-06-29 18:11
At first read, similar to #146.  Must read the details

**Comment by qzhang234** [comment] 2020-06-29 18:14
RIght. That's what I'm afraid of. I thought XSPA doesn't have this IOC problem because it's not communicating with EPICS at all except for one UniDig and one nc command?

**Comment by prjemian** [comment] 2020-06-29 18:15
Exactly.

**Comment by qzhang234** [comment] 2020-06-29 18:16
Let me know if there's anything you want me to provide. I'm not in a hurry to run anything at this moment and I would prefer that the Rigaku team can take a loot at the XSPA status too

**Comment by qzhang234** [comment] 2020-06-29 18:17
Now that I recall, ever since we started running Bluesky it has always been error with hanging. This type of crash is a first

**Comment by prjemian** [comment] 2020-06-29 18:41
Looks like a python error this time different from #146

```
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/subprocess.py", line 1441, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
```

**Comment by prjemian** [comment] 2020-06-29 18:47
FYI: this seems relevant: https://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files

**Comment by prjemian** [comment] 2020-06-29 18:53
Most of the proposed changes in that StockOverflow posting require SysAdmin privileges to execute.  I believe the problem is how the [`subprocess`]() module is called in our code, that we are not closing the files (and pipes) as we thought we were.

Another bug reports on this ... https://bugs.python.org/issue3210 and [more](https://duckduckgo.com/?t=ffsb&q=python+subprocess+OSError%3A+%5BErrno+24%5D+Too+many+open+&ia=web)

**Comment by prjemian** [comment] 2020-06-29 18:55
Here's our call:
https://github.com/aps-8id-dys/ipython-8idiuser/blob/afc46679463020c946ee9bebbfb53a86efec22f2/profile_bluesky/startup/instrument/devices/rigaku_ufxc.py#L43-L49

**Comment by qzhang234** [comment] 2020-06-29 18:56
The one on StackOverflow looks almost exactly the same as ours, even the part where the person said it crashes after a few thousand runs. 

But I thought you are the SysAdmin?

**Comment by prjemian** [comment] 2020-06-29 18:57
Maybe we need to close the `self.process` here, between lines 53 & 54? https://github.com/aps-8id-dys/ipython-8idiuser/blob/afc46679463020c946ee9bebbfb53a86efec22f2/profile_bluesky/startup/instrument/devices/rigaku_ufxc.py#L51-L54

**Comment by prjemian** [comment] 2020-06-29 18:59
This: `self.process.close()`, then `self.process = None`.  Needs testing.

**Comment by qzhang234** [comment] 2020-06-29 19:01
Like this?

```

 @apstools.utils.run_in_thread 
 def watch_process(): 
     self.unix_output, self.unix_error = self.process.communicate() 
     status._finished() 
     self.process.close()
     self.process = None

```

**Comment by prjemian** [comment] 2020-06-29 19:04
You want this code to happen *before* we declare the status is finished.  So:

```
 @apstools.utils.run_in_thread 
 def watch_process(): 
     self.unix_output, self.unix_error = self.process.communicate() 
     self.process.close()
     self.process = None
     status._finished() 
```

**Comment by prjemian** [comment] 2020-06-29 19:05
1. get the values from the UNIX process
2. maintenance work: close the processing pipeline
3. tell ophyd that our device's activities are finished

**Comment by qzhang234** [comment] 2020-06-29 19:06
Got it. I'll implement this and submit some long measurement. Will let you know if it works

**Comment by qzhang234** [comment] 2020-06-29 22:06
@prjemian It crashed after the change:

```

In [4]: _ = RE(multi_capil())                                                                                                     
Ta138_D100_Fly0p1_att02_0001                                                                                                      
Exception in thread Thread-234:                                                                                                   
Traceback (most recent call last):
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/devices/rigaku_ufxc.py", line 59, in watch_process
    self.process.close()
AttributeError: 'Popen' object has no attribute 'close'

^CA 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
^Ctrying a second time
^C

^CA 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
^Ctrying a second time
^C^C^C^C^C

```

**Comment by prjemian** [comment] 2020-06-29 23:19
Ouch!  That was not such good advice, then.  Looking at [subprocess](), that's right, there is no `close()` command:

```
In [1]: import subprocess

In [3]: dir(subprocess.Popen)
Out[3]: 
['__class__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_timeout',
 '_child_created',
 '_communicate',
 '_execute_child',
 '_get_devnull',
 '_get_handles',
 '_handle_exitstatus',
 '_internal_poll',
 '_remaining_time',
 '_save_input',
 '_stdin_write',
 '_translate_newlines',
 '_try_wait',
 '_wait',
 'communicate',
 'kill',
 'poll',
 'send_signal',
 'terminate',
 'universal_newlines',
 'wait']
```

**Comment by prjemian** [comment] 2020-06-29 23:22
Delete the line `self.process.close()` and see if this satisfies the `Too many open files` problem.  By setting `self.process` to `None` it drops the reference to the `Popen` object and allows associated files to be closed and the object to be garbage collected.  In principle.

**Comment by qzhang234** [comment] 2020-06-29 23:50
Good idea. Also does close Bluesky terminal have similar (and maybe more guaranteed) effect? We did have ~ 28,000 measurements done before this error happened ...

**Comment by prjemian** [comment] 2020-06-29 23:51
yes

**Comment by qzhang234** [comment] 2020-06-29 23:52
Got it. Will do both for now.

**Comment by prjemian** [comment] 2020-06-29 23:52
While that sounds like a pre-emptive idea that works.  I hope that we _fix_ this problem.

**Comment by qzhang234** [comment] 2020-06-30 05:03
Submitted overnight scan, B148 and B149, both have 10,000 measurements. @sureshnaps I created a new folder; @prjemian The above-mentioned change has been implemented.

Let's wait till tomorrow to find out if it works

**Comment by prjemian** [comment] 2020-06-30 15:11
By the way, the [IT group](https://github.com/aps-8id-dys/ipython-8idiuser/issues/188#issuecomment-651299430) are the [SysAdmins](https://github.com/aps-8id-dys/ipython-8idiuser/issues/188#issuecomment-651297920).

**Closed** 2020-06-30 16:47 UTC
Labels: high priority
